language: node_js
node_js: 11.14.0

jobs:
  include:
    - stage: "Node tests"
      name: "shallow rendering components"
      script: npm test --directory src/tests

    # use the following to add other test suites for travis to run
    # stages will run in paralell, but scripts within a stage will run in sequence
    #
    # name: "name or brief description of the suite"
    # script: npm test --directory path/to/suite


branches:
  except:
    - /documentation.*/
    - /doc_.*/